# Generated by Django 5.0 on 2023-12-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Date and Time")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="Modificatioin Date and Time")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("tipo", models.CharField(max_length=100, verbose_name="Tipo")),
            ],
            options={
                "ordering": ("tipo",),
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="bread",
            options={"ordering": ("tipo",)},
        ),
        migrations.AlterModelOptions(
            name="meat",
            options={"ordering": ("tipo",)},
        ),
        migrations.AlterModelOptions(
            name="optional",
            options={"ordering": ("tipo",)},
        ),
    ]
