# Generated by Django 5.0 on 2023-12-29 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_status_alter_bread_options_alter_meat_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="optional",
            options={"ordering": ("tipo",), "verbose_name_plural": "Optional"},
        ),
        migrations.AlterModelOptions(
            name="status",
            options={"ordering": ("tipo",), "verbose_name_plural": "status"},
        ),
        migrations.CreateModel(
            name="Burger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Date and Time")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="Modificatioin Date and Time")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("name", models.CharField(max_length=50, verbose_name="nome")),
                (
                    "bread",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.bread", verbose_name="pao"),
                ),
                (
                    "meat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.meat", verbose_name="carne"
                    ),
                ),
                ("optionais", models.ManyToManyField(to="core.optional", verbose_name="opcionais")),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.status", verbose_name="status"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
