# Generated by Django 5.0 on 2023-12-29 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_optional_options_alter_status_options_burger"),
    ]

    operations = [
        migrations.RenameField(
            model_name="burger",
            old_name="meat",
            new_name="carne",
        ),
        migrations.RenameField(
            model_name="burger",
            old_name="name",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="burger",
            old_name="optionais",
            new_name="opcionais",
        ),
        migrations.RenameField(
            model_name="burger",
            old_name="bread",
            new_name="pao",
        ),
    ]
